-- 코드를 입력하세요
SELECT MEMBER_ID , MEMBER_NAME, GENDER,date_format(DATE_OF_BIRTH, '%Y-%m-%d')
from MEMBER_PROFILE
where MONTH(DATE_OF_BIRTH) = 03
    AND TLNO IS NOT NULL
    AND GENDER = 'W'
ORDER BY MEMBER_ID
